services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8080:8080"
    environment:
      - KINESIS_PREDICTIONS_STREAM_NAME=${KINESIS_PREDICTIONS_STREAM_NAME}
      - KINESIS_ENDPOINT_URL=http://kinesis:4566/
      - KINESIS_REGION_NAME=ru-central1
      - KINESIS_PREDICTIONS_CLOUD_NAME=None
      - KINESIS_PREDICTIONS_DB_NAME=None
      - RUN_ID=Test123
      - MODEL_LOCATION=/app/model
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=xyz
    volumes:
      - "./model:/app/model"
  kinesis:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis
